receivers:
  dynatrace:
    API_ENDPOINT: ${env:API_ENDPOINT}
    API_TOKEN: ${env:API_TOKEN}
    metric_selectors:
      - builtin:containers.cpu.usageTime
      - builtin:containers.memory.residentSetBytes
      - builtin:host.disk.writeTime
      - builtin:host.disk.readTime
      - builtin:host.disk.used
      - builtin:host.disk.avail
      - builtin:host.net.nic.trafficOut
      - builtin:host.net.nic.trafficIn 
      - builtin:kubernetes.node.conditions
    resolution: 1m # 1m
    from: "2025-04-01T00:00:00Z" # now-1m 
    to: "2025-04-02T00:00:00Z" # now  
    poll_interval: 30s 
    max_retries: 3
    http_timeout: 10s
    tls_settings:
      insecure_skip_verify: true # added to skip TLS verification when dealing with self-signed certificates

exporters:
  # otlphttp:
    # endpoint: http://localhost:4318  
  debug:

processors:
  batch:
    timeout: 5s             # flush every 5 seconds (adjust as needed)
    send_batch_size: 500    # max number of data points per batch
  resource:
    attributes:
      - key: environment
        value: ${env:DEPLOYMENT_ENVIRONMENT}  # prod, stage, test, dev
        action: upsert
      - key: project_name
        value: ${env:PROJECT_NAME}            # inject your project/cluster name dynamically
        action: upsert
      - key: team_owner
        value: "team-sid"
        action: insert
      - key: region
        value: ${env:DEPLOYMENT_REGION}       # optional region or location if applicable
        action: upsert

service:
  telemetry:
    logs:
      level: debug
  pipelines:
    metrics:
      receivers: [dynatrace]
      processors: [resource, batch]
      exporters: [debug] # otlphttp

